### ISSUE TITLE
Deployment script doesn't select npm version

### ISSUE THREAD

**Issue by ethanroday** [Azure-Samples/meanjs#4]
The custom deployment script fails to pick the correct version of `npm` when the `node` version is constrained in `package.json`. This appears to be due to a typo in L81, which should be:
```if [[ -e "$DEPLOYMENT_TEMP/__npmVersion.tmp" ]]; then```

**Comment by xtianus79** [comment]
@ethanroday doesn't select node version correctly either

**Comment by prashanthmadi** [comment]
@ethanroday @xtianus79  Thanks for reporting this issue. 
Which version of nodejs are you using in package.json ?

**Comment by xtianus79** [comment]
The versions of node is per se what comes in the engine property of the package.json... so it should be 6.7 i believe

**Comment by prashanthmadi** [comment]
@xtianus79 any reason for using 6.7 if there is 6.11 

I have written below blog on npm and nodejs versions in app services
https://blogs.msdn.microsoft.com/azureossds/2016/04/20/nodejs-and-npm-versions-on-azure-app-services/

I would recommend to set same version of nodejs in app setting as well as package.json that clears a lot of issues.

Also, I will check on that L81 and update soon

**Comment by xtianus79** [comment]
@prashanthmadi Are you realizing this is a pakage that is built by you guys or in the least by mongodb?  

```
  },
  "engines": {
    "node": "6.9.1",
    "npm": "3.10.8"
  },
```

This is from this very repo... 

Azure webapps will use the, or is supposed to use, the engine: node version of the package.json.  

We should be using node 7 or even 8 for that matter but in the least 6.9 or 6.7 or 6.11 should work.  

the issue is something is wrong the bash script... it is blocking the listed version of node from being installed/used correclty by the Azure webapp

**Comment by xtianus79** [comment]
@cephalin Looking at these comments... I am questioning the knowledge and capacity of the node team.  I would love to help with the project if you would like.  There are amazing things you guys have but the documentation and seemingly the general understanding seem a bit off.  room for one more?

**Comment by prashanthmadi** [comment]
@xtianus79 I have updated deploy.sh 

https://github.com/Azure-Samples/meanjs/commit/05d2f7c8972836763464127f9786e5adb8340317
